// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_OdqbCRG-7ga7wdAW4r0Dn7fTkL6thVY',
    appId: '1:51099885723:web:476764c9c2319b8c34a63e',
    messagingSenderId: '51099885723',
    projectId: 'hoven-flutter-app',
    authDomain: 'hoven-flutter-app.firebaseapp.com',
    databaseURL: 'https://hoven-flutter-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hoven-flutter-app.appspot.com',
    measurementId: 'G-88D1G9BKZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACjMg66tsrcXKJQ1UIbzXxx5S6BUWsmj4',
    appId: '1:51099885723:android:eb974f9bf2bd34b534a63e',
    messagingSenderId: '51099885723',
    projectId: 'hoven-flutter-app',
    databaseURL: 'https://hoven-flutter-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hoven-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA--pVKNJXsTwe8iwFE2bJyc-ofGzvDYuA',
    appId: '1:51099885723:ios:69773e54a2122d7434a63e',
    messagingSenderId: '51099885723',
    projectId: 'hoven-flutter-app',
    databaseURL: 'https://hoven-flutter-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hoven-flutter-app.appspot.com',
    iosBundleId: 'test.rakshak.firstFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA--pVKNJXsTwe8iwFE2bJyc-ofGzvDYuA',
    appId: '1:51099885723:ios:d50f081b1a4aa39c34a63e',
    messagingSenderId: '51099885723',
    projectId: 'hoven-flutter-app',
    databaseURL: 'https://hoven-flutter-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hoven-flutter-app.appspot.com',
    iosBundleId: 'test.rakshak.firstFlutterProject.RunnerTests',
  );
}
